language: cpp

compiler:
  - gcc

before_install:
    # Add software package repository, containing updated build toochain, i.e. GNU GCC 4.8
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test --yes
  - sudo apt-add-repository ppa:boost-latest/ppa --yes
  - sudo apt-add-repository ppa:chris-lea/zeromq --yes
  - sudo add-apt-repository ppa:kalakris/cmake --yes
  - sudo apt-get update -qq

install:
  - sudo apt-get install -q libboost-program-options1.55-dev g++-4.9 gcc-4.9 libzmq3-dev valgrind cmake protobuf-compiler libprotobuf-dev libprotoc-dev
  - export CXX="g++-4.9" CC="gcc-4.9"
  - git submodule init
  - git submodule update
  - mkdir build && cd build

script:
  - cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX:PATH=../run
  - make all
  - make test
  - make test_memcheck
